# Generated by Django 4.2 on 2023-04-28 06:06

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True)),
                ('created_by', models.IntegerField(null=True)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_by', models.IntegerField(null=True)),
                ('updated_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('name', models.CharField(max_length=128)),
                ('code', models.CharField(max_length=32, null=True, verbose_name='Department code')),
            ],
            options={
                'db_table': 'department',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True)),
                ('created_by', models.IntegerField(null=True)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_by', models.IntegerField(null=True)),
                ('updated_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('name', models.CharField(max_length=128)),
                ('age', models.IntegerField()),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='org.department')),
            ],
            options={
                'db_table': 'employee',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True)),
                ('created_by', models.IntegerField(null=True)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_by', models.IntegerField(null=True)),
                ('updated_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('name', models.CharField(max_length=256)),
            ],
            options={
                'db_table': 'school',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SchoolZone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True)),
                ('created_by', models.IntegerField(null=True)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_by', models.IntegerField(null=True)),
                ('updated_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('name', models.CharField(max_length=256)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='org.school')),
            ],
            options={
                'db_table': 'school_zone',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SchoolZoneSupervisor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True)),
                ('created_by', models.IntegerField(null=True)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_by', models.IntegerField(null=True)),
                ('updated_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('assume_start_date', models.DateField()),
                ('assume_end_date', models.DateField(null=True)),
                ('school_zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='org.schoolzone')),
            ],
            options={
                'db_table': 'school_zone_supervisor',
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='department',
            name='school_zone',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='org.schoolzone'),
        ),
        migrations.CreateModel(
            name='Supervisor',
            fields=[
                ('employee_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='org.employee')),
                ('post', models.CharField(max_length=128)),
                ('school_zones', models.ManyToManyField(through='org.SchoolZoneSupervisor', to='org.schoolzone')),
            ],
            options={
                'db_table': 'supervisor',
                'abstract': False,
            },
            bases=('org.employee',),
        ),
        migrations.AddField(
            model_name='schoolzonesupervisor',
            name='supervisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='org.supervisor'),
        ),
    ]
