# Generated by Django 4.2 on 2023-04-23 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='created_by',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='choice',
            name='updated_by',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='created_by',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='updated_by',
            field=models.IntegerField(null=True),
        ),
    ]
