# Generated by Django 4.2 on 2023-04-28 03:24

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_place_restaurant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True)),
                ('created_by', models.IntegerField(null=True)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_by', models.IntegerField(null=True)),
                ('updated_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('name', models.CharField(max_length=128)),
                ('age', models.IntegerField(null=True)),
                ('restaurants', models.ManyToManyField(to='polls.restaurant')),
            ],
            options={
                'db_table': 'manager',
                'abstract': False,
            },
        ),
    ]
